# cargo

# [[file:~/Workspace/Programming/gchemol-rs/gchemol-core/gchemol-core.note::*cargo][cargo:1]]
[package]
name = "gchemol-core"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
indexmap = {version="1", features=["serde-1"]}
serde = {version="1", features = ["derive"]}
nxgraph = { path = "../nxgraph" }
guts = { git = "https://github.com/ybyygu/guts.git" }

[dev-dependencies]
# cargo:1 ends here
